sudo: false
dist: trusty

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

jobs:
  include:
    - stage: test
      script: cargo test -j8
      rust:
        - stable
        - beta
        - nightly

    - stage: code_coverage
      script: bash ./ci/check_code_coverage.sh
      rust: stable

    - stage: release
      script: cargo build -j8 --release
      rust: stable
