language: rust
sudo: false
cache: cargo

branches:
  only:
  - master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

jobs:
  include:
    - stage: test
      script: cargo test -j8
      rust: nightly
      allow_failures:
        rust: nightly

    - stage: code_coverage
      script: bash ./ci/check_code_coverage.sh
      rust: stable

    - stage: release
      script: cargo build -j8 --release
      rust: stable
