sudo: false
cache: cargo
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

matrix:
  allow_failures:
    - rust: nightly
  jobs:
    include:
      - stage: test
        rust:
          - stable
          - beta
          - nightly
        script: cargo test -j8
      - stage: code coverage
        rust:
          - stable
        script: bash ./ci/check_code_coverage.sh
      - stage: release
        rust:
          - stable
        script: cargo build -j8 --release
