sudo: false
cache: cargo
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

branches:
  only:
    - master
    - develop

jobs:
  include:
  - stage: test
    rust:
    - stable
    - beta
    - nightly
    script: cargo test -j8
  - stage: code coverage
    rust:
    - stable
    - beta
    - nightly
    script: bash ./ci/check_code_coverage.sh
  - stage: release
    rust:
    - stable
    - beta
    - nightly
    script: cargo build -j8 --release
