language: rust
sudo: required
services:
- docker

branches:
  only:
  - master

before_install:
- docker pull edattore/travis-rust

jobs:
  allow_failures:
  - rust: nightly
  include:
    - &test-all-rust-versions
      stage: test
      rust: stable
      script: docker run edattore/travis-rust /bin/sh -c "/root/.cargo/bin/cargo test"
    - <<: *test-all-rust-versions
      rust: beta
      script: docker run edattore/travis-rust /bin/sh -c "/root/.cargo/bin/cargo test"
    - <<: *test-all-rust-versions
      rust: nightly
      script: docker run edattore/travis-rust /bin/sh -c "/root/.cargo/bin/cargo test"
    - stage: code_coverage
      script: docker run edattore/travis-rust /bin/sh -c "bash ./ci/check_code_coverage.sh"
      rust: stable
    - stage: release
      script: docker run edattore/travis-rust /bin/sh -c "cargo build -j8 --release"
      rust: stable
