sudo: false
cache: cargo
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

branches:
  only:
    - master
    - develop

script:
  - |
      RUSTFLAGS="$RUSTFLAGS -C link-dead-code" cargo test -j8

after_success: >
  if [[ $TRAVIS_RUST_VERSION = 'stable' ]]; then
    wget https://github.com/SimonKagstrom/kcov/archive/v33.tar.gz
    tar xzf v33.tar.gz
    cd kcov-33
    mkdir build
    cd build
    cmake ..
    make
    cd ../..
    ./kcov-33/build/src/kcov --verify --exclude-pattern=/.cargo target/kcov target/debug/aluminum-* &&
    ./kcov-33/build/src/kcov --coveralls-id=$TRAVIS_JOB_ID --verify --exclude-pattern=/.cargo,tests/lib.rs,src/main.rs target/kcov target/debug/lib-*
  fi
