sudo: false
cache: cargo
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: test
      script: cargo test -j8
    - stage: code coverage
      script: bash ./ci/check_code_coverage.sh
    - stage: release
      script: cargo build -j8 --release
