# TODO: Add back the apt packages required to build kcov - doh!
language: rust
cache: cargo
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
_yaml_anchors:
- &test_stage_anchor
  stage: Test
  script: cargo test -j8
branches:
  only:
  - master
jobs:
  allow_failures:
  - rust: nightly
  include:
  - <<: *test_stage_anchor
    rust: stable
  - <<: *test_stage_anchor
    rust: beta
  - <<: *test_stage_anchor
    rust: nightly
  - stage: Code Coverage
    script: cargo test -j8 --no-run && ./ci/check_code_coverage.sh
    rust: stable
    env:

